### ISSUE TITLE
Unable to create keystore for A-MQ

### ISSUE THREAD

**Issue by noelo** [jboss-fuse/amq-openshift-cartridge#19]
When creating an instance using 
 "rhc create-app -e OPENSHIFT_AMQ_PASSWORD=admin amq http://is.gd/Q5ihum" 

the OPENSHIFT_AMQ_PASSWORD needs to be 6 characters or more else the keytool command used to generate the A-MQ keystore will fail with 

keytool error: java.lang.Exception: Key password must be at least 6 characters"

**Comment by chirino** [comment]
Your password must be at least 6 characters long as the error states.
